### ISSUE TITLE
Deploy terraform config to GCP using GitHub Actions

### ISSUE THREAD

**Issue by BryceBeagle** [shortcake-dev/shortcake-terraform#7]
- [x] dev
    - [x] On PR open/commit: Deploy to `shortcake-dev` GCP project (#8)
    - [x] Ensure that PRs don't share resources on `shortcake-dev` GCP project (#11)
    - [x] On PR close: Destroy deployment on `shortcake-dev` GCP project (#14)
    - [x] Prevent concurrent runs (#15)
- [x] staging
    - [x] On commit to `main`: Deploy to `shortcake-staging` GCP project (#16)
- [ ] prod
    - [ ] On release tag: Deploy to `shortcake-prod` GCP project
